### ISSUE TITLE
window undefined

### ISSUE THREAD

**Issue by Jackie-5** [KyleAMathews/element-resize-event#19]
I rely on the echarts-for-react the package depends on your bag, but because your bag in the update cause in error in my code, trouble update before test.

**Comment by Jackie-5** [comment]
TEX~

**Comment by Guibod** [comment]
Same as #17  ? Version 2.0.9 fixes that.

**Comment by laurence-hudson-tessella** [comment]
I'm actually seeing this as result of upgrading from 2.0.7 to 2.0.9, so introduced in 2.0.9 rather than fixed. For context, I'm consuming `element-resize-event` via `react-dimension` in a webpacked  `electron` (chrome) browser environment. Might something like `var window = global.window || this` be a safer way of achieving what was implemented in #18.

**Comment by lkostrowski** [comment]
Had same problem after update to 2.0.9, downgrade to 2.0.7 fixed

**Comment by stel** [comment]
+1 here

**Comment by suprise** [comment]
+1 here

**Comment by jason-rachio** [comment]
+1 here

**Comment by KyleAMathews** [comment]
Any of you want to submit a PR?

**Comment by jason-rachio** [comment]
Perhaps, do we just need to do something like they're doing here:  https://github.com/istarkov/google-map-react/blob/b8bf3ad03fb22a11d2aa573406febda5bdc9f2ed/src/utils/detectElementResize.js

```
var canUseDOM = !!(
    (typeof window !== 'undefined' &&
    window.document && window.document.createElement)
);

// Check `document` and `window` in case of server-side rendering
var _window
if (canUseDOM) {
  _window = window
} else if (typeof self !== 'undefined') {
  _window = self
} else {
  _window = this
}
```

**Comment by drcmda** [comment]
Right now element-resize-event crashes our build : (

@KyleAMathews wouldn't it be ok to simply drop the polyfill altogether? All evergreen browsers have it and it should be the users responsibility to fetch workarounds when it's really not available. When you have about 20 RAF polyfills in the bundle eventually because each dependency ships their own it's questionable if that's really the way forward. Instead i think they should declare dependencies on browser features.

Edit: added a PR

**Comment by jsthivierge** [comment]
+1

**Comment by matejbudzel** [comment]
+1

**Comment by HannaBabrouskaya** [comment]
+1

**Comment by hustcc** [comment]
@KyleAMathews Can do something help to fix it?


Four month later, I rewrite it with [size-sensor](https://github.com/hustcc/size-sensor), `this` in javascript is really confusing.
